version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9.14
    working_directory: ~/wayscript-python
    steps:
      - setup_remote_docker:
          version: 20.10.20
      - checkout
      - run:
          name: lint
          command: docker-compose -f docker-compose.ci.yml run --rm app lint
      - run:
          name: test
          command: docker-compose -f docker-compose.ci.yml run --rm app test
